name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    push:
        branches: main
jobs:
    jobs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install 
            - run: npm test
    jobs2:
        runs-on: ubuntu-latest
        steps:
            - run: npm test
    jobs3:
        runs-on: ubuntu-latest
        steps:
            - run: npm install 
            - run: npm test
    jobs4:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm test
    checkout:
        runs-on: ubuntu-latest
        steps:
            - run: ls -al

